# Generated by Django 5.2.9 on 2025-12-20 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Bloque 1, Bloque Mañana', max_length=50, verbose_name='Nombre del bloque')),
                ('start_time', models.TimeField(verbose_name='Hora inicio')),
                ('end_time', models.TimeField(verbose_name='Hora fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bloque Horario',
                'verbose_name_plural': 'Bloques Horarios',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ReservationRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_hours_per_day', models.PositiveIntegerField(default=2, help_text='Horas máximas que un usuario puede reservar por día', verbose_name='Máximo de horas por día')),
                ('max_days_in_advance', models.PositiveIntegerField(default=2, help_text='Cuántos días hacia el futuro se puede reservar', verbose_name='Días máximos de anticipación')),
                ('max_active_reservations', models.PositiveIntegerField(default=5, help_text='Cantidad máxima de reservas activas simultáneas por usuario', verbose_name='Máximo de reservas activas')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Configuración de Reglas',
                'verbose_name_plural': 'Configuración de Reglas',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la sala')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacidad (personas)')),
                ('location', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('is_public', models.BooleanField(default=True, help_text='Si está desmarcado, solo el admin puede reservar esta sala', verbose_name='Sala pública')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_materials', models.ManyToManyField(blank=True, related_name='rooms', to='reservas.material', verbose_name='Materiales disponibles')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('reason', models.CharField(help_text='Ej: Mantenimiento, Evento especial', max_length=200, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to='reservas.room', verbose_name='Sala')),
                ('time_block', models.ForeignKey(blank=True, help_text='Dejar vacío para bloquear todo el día', null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.timeblock', verbose_name='Bloque horario')),
            ],
            options={
                'verbose_name': 'Bloqueo de Sala',
                'verbose_name_plural': 'Bloqueos de Salas',
                'ordering': ['-date', 'room'],
                'unique_together': {('room', 'date', 'time_block')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('completed', 'Completada')], default='confirmed', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_materials', models.ManyToManyField(blank=True, related_name='reservations', to='reservas.material', verbose_name='Materiales solicitados')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservas.room', verbose_name='Sala')),
                ('time_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.timeblock', verbose_name='Bloque horario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-date', 'time_block'],
                'unique_together': {('room', 'date', 'time_block', 'status')},
            },
        ),
    ]
