# Generated by Django 5.2.9 on 2025-12-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeblock',
            options={'ordering': ['day_of_week', 'start_time'], 'verbose_name': 'Bloque Horario', 'verbose_name_plural': 'Bloques Horarios'},
        ),
        migrations.AddField(
            model_name='timeblock',
            name='day_of_week',
            field=models.CharField(choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], default='monday', help_text='Día al que aplica este bloque horario', max_length=10, verbose_name='Día de la semana'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeblock',
            name='name',
            field=models.CharField(help_text='Ej: Bloque 1, Bloque Mañana, Sábado Tarde', max_length=50, verbose_name='Nombre del bloque'),
        ),
        migrations.AlterUniqueTogether(
            name='timeblock',
            unique_together={('day_of_week', 'start_time', 'end_time')},
        ),
    ]
