# Generated by Django 5.2.9 on 2025-12-21 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_timeblock_options_timeblock_day_of_week_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('student', 'Estudiante'), ('teacher', 'Profesor'), ('staff', 'Personal'), ('admin', 'Administrador')], max_length=50, unique=True, verbose_name='Tipo de rol')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('can_reserve', models.BooleanField(default=True, verbose_name='Puede reservar')),
                ('can_reserve_internal_rooms', models.BooleanField(default=False, verbose_name='Puede reservar salas internas')),
                ('max_hours_override', models.PositiveIntegerField(blank=True, help_text='Dejar vacío para usar la regla global', null=True, verbose_name='Horas máximas (sobrescribe regla global)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alma_user_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID de Alma')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='Facultad/Carrera')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='reservas.role', verbose_name='Rol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
