# Generated by Django 5.2.9 on 2025-12-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_role_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['-priority', 'name'], 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AddField(
            model_name='role',
            name='display_name',
            field=models.CharField(default='Rol', help_text='Nombre amigable que se mostrará en la interfaz', max_length=100, verbose_name='Nombre para mostrar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Mayor número = mayor prioridad (útil para casos de conflicto)', verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_reserve',
            field=models.BooleanField(default=True, help_text='Si puede hacer reservas de salas', verbose_name='Puede reservar'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_reserve_internal_rooms',
            field=models.BooleanField(default=False, help_text="Acceso a salas marcadas como 'uso interno'", verbose_name='Puede reservar salas internas'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, help_text='Describe los permisos y alcance de este rol', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='role',
            name='max_hours_override',
            field=models.PositiveIntegerField(blank=True, help_text='Deja vacío para usar la regla global. Si defines un valor, sobrescribe la regla global para este rol.', null=True, verbose_name='Horas máximas por día (opcional)'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='Ej: Estudiante, Profesor, Investigador, etc.', max_length=50, unique=True, verbose_name='Nombre del rol'),
        ),
    ]
